Added check of EDSS_SUBSYS e.v., but removed manual setting

diff --git a/setup/Setup b/setup/Setup
--- a/setup/Setup
+++ b/setup/Setup
@@ -9,8 +9,10 @@
 #
 ##################################################################
 
-setenv EDSS_SUBSYS /env/proj/edss/subsys
-
+if ( $?EDSS_SUBSYS ) then
+else
+   echo "ERROR: EDSS Tools \"Setup\" script requires setting of the EDSS_SUBSYS"
+   echo "       environment variable prior to using it."
 
 #  Set directories
    source set_dirs.scr
